apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |-
    [server]
    protocol = http
    http_port = 3000
    domain = localhost
    enforce_domain = false
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [analytics]
    reporting_enabled = false
    check_for_updates = true
    [security]
    admin_user = admin
    admin_password = admin
    [users]
    allow_sign_up = false
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
