version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.22.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.1.5
    volumes:
      - ./grafana-config.yaml:/etc/grafana/grafana.ini
      - ./dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
